macro(scan_files return_list input_dir extension recurse)
    if(${recurse})
        file(GLOB_RECURSE new_list RELATIVE ${input_dir} ${input_dir}/*${extension})
    else ()
        file(GLOB new_list RELATIVE ${input_dir} ${input_dir}/*${extension})
    endif ()
    set(files_list "")
    foreach (file_path ${new_list})
        list(APPEND files_list ${input_dir}/${file_path})
    endforeach ()
    list(REMOVE_DUPLICATES files_list)
    set(${return_list} ${files_list})
endmacro()

macro(scan return_list input_dir extension)
    scan_files(${return_list} ${input_dir} ${extension} false)
endmacro()

macro(scan_recurse return_list input_dir extension)
    scan_files(${return_list} ${input_dir} ${extension} true)
endmacro()

macro(exclude_dir dir_name filtering_list)
    set(to_remove "")
    foreach (file_path ${${filtering_list}})
        set(found "")
        string(FIND ${file_path} ${dir_name} found)
        if(found GREATER -1)
            list(APPEND to_remove ${file_path})
        endif ()
    endforeach ()
    foreach (path ${to_remove})
        list(REMOVE_ITEM ${filtering_list} ${path})
    endforeach ()
    message(STATUS "${filtering_list}")
endmacro()

macro(scan_dirs dir_name result)
    file(GLOB children RELATIVE ${dir_name} ${dir_name}/*)
    set(dir_names "")
    foreach (child ${children})
        if(IS_DIRECTORY ${dir_name}/${child})
            list(APPEND dir_names ${child})
        endif ()
    endforeach ()
    set(${result} ${dir_names})
endmacro()

macro(have_cmake dir_name result)
    file(GLOB children RELATIVE ${dir_name} ${dir_name}/CMakeLists.txt)
    list(LENGTH children count)
    if(${count} EQUAL 1)
        set(${result} true)
    else ()
        set(${result} false)
    endif ()
endmacro()